gems: ['jekyll-lunr-js-search']

markdown: redcarpet
permalink: /:categories/:title.html
url:
lsi: false
highlighter: pygments
safe: false

paginate: 8
paginate_path: "page:num"

# presonal config
domain: out001a.github.io
title: Huanming's Blog
description: Web, Mobile, PHP, Linux, 阅读与思考, 感悟与牢骚, ...
author: shanhuanming
email: out001a#gmail.com
github: out001a
weibo: out001a

config:
  js_dir:
  img_dir:
  css_dir:
