markdown: redcarpet
permalink: /:categories/:title.html
url:
lsi: false
highlighter: pygments
safe: true

paginate: 8
paginate_path: "page:num"

# presonal config
domain: out001a.github.io
title: Huanming's Blog
description: PHP, Web, Linux, reading...
author: shanhuanming
email: out001a#gmail.com
github: out001a

config:
  js_dir:
  img_dir:
  css_dir:
